import type { Metadata } from "next";
import {Nunito } from "next/font/google";
import "./globals.css";


const nunito = Nunito({
  subsets: ["latin"],
  weight: ["400", "700"],
  style: ["normal", "italic"],
  variable: "--font-nunito",
});
export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "FruitGuard",

  icons:{
    icon:"/Images/fruitguard.png"
  }
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunito.variable} font-nunito`}
      >
        {children}
      </body>
    </html>
  );
}
